---
title: "Utility Functions"
output: html_notebook
---

Contains regularly used text functions while debugging. 

```{r}
# Find tokens which have over a given no of characters
cmv_spacy_tokens %>%
  subset(nchar(token) > 20)
```

```{r}
# Frequencies of features in a dfm
featfreq(cmv_text_dfm)
```

```{r}
# Scaling
scale(k_search_output$results$K, center = TRUE, scale = TRUE)
```

```{r}
# textstat_summary
cmv_text_summary <- textstat_summary(cmv_text_corpus)
# Extract indices of documents from textstat_summary
idx <- which(cmv_text_summary$urls > 0)
```


```{r}
# Intermediary tests

# Find the POS tag of a given token
cmv_spacy_tokens %>%
  subset(token == "disproportionately")
```

```{r}
# Find unique tokens for a given POS tag
cmv_spacy_tokens %>%
  subset(pos == "ADV") %>%
  group_by(lemma) %>%
  summarize(count = n()) %>%
  arrange(desc(count))
```


```{r}
# Test corpus
txt <- c(doc1 = "Minorities were targeted disproportionately.", 
          doc2 = "This literally makes no sense.",
          doc3 = "Tell me when you just come" )
spacy_parse(txt, tag = TRUE)
```


```{r}
# Find how a token is located within a document
kwic(cmv_spacy_tokens %>% as.tokens(use_lemma = TRUE), pattern = "%", valuetype = "regex", window = 10)
```

